apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: food-clustering
type: Opaque
stringData:
  DB_PASSWORD: "YourStrong@Passw0rd"
  MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
  MSSQL_DATABASE: "food_clustering"
  MSSQL_USERNAME: "sa"
