apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-master
        image: bitnami/spark:3.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
          name: master
        - containerPort: 8080
          name: ui
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark-cluster
spec:
  selector:
    app: spark-master
  ports:
  - port: 7077
    targetPort: 7077
    name: master
  - port: 8080
    targetPort: 8080
    nodePort: 30808
    name: ui
  type: NodePort
