apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: ui
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark-master:7077"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
