apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: {{ .Values.namespace }}
data:
  MSSQL_PID: {{ .Values.mssql.pid }}
  DB_SERVER: "mssql-service"
  DB_PORT: "1433"
  DB_NAME: {{ .Values.secrets.mssql.database }}
  DB_USER: {{ .Values.secrets.mssql.username }}
