apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: {{ .Values.mssql.image }}
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MSSQL_SA_PASSWORD
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: MSSQL_PID
        resources:
          requests:
            memory: {{ .Values.mssql.resources.requests.memory | quote }}
            cpu: {{ .Values.mssql.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.mssql.resources.limits.memory | quote }}
            cpu: {{ .Values.mssql.resources.limits.cpu | quote }}
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP
