apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MSSQL_DATABASE: {{ .Values.secrets.mssql.database | b64enc }}
  MSSQL_USERNAME: {{ .Values.secrets.mssql.username | b64enc }}
  MSSQL_SA_PASSWORD: {{ .Values.secrets.mssql.password | b64enc }}
